#Honor Pledge: I pledge that I have neither
#given nor received any undue help on this assignment.
#
#strangni
#
#CS 240 - Assignment 3 - Roster Generator
#Created by: Nicholas Strange

Driver.class: Driver.java Player.class
	javac Driver.java
	
Player.class: Player.java
	javac Player.java
	
clean: 
	rm Driver.class Player.class
	
run: Driver.class
	java Driver
	
